spring:
  profiles:
    active: local
    group:
      local: console-logging
      dev: console-logging
      prod: console-logging
  application:
    name: re_cipe-backend
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/recipe;MODE=MYSQL
    username: sa
    password:
  OAuth2:
    google:
      client_id: ${oauth2.google.client-id}
      client_secret: ${oauth2.google.client-secret}
      url:
        redirect: ${oauth2.google.url.redirect}
        token: https://oauth2.googleapis.com/token
        profile: https://www.googleapis.com/oauth2/v3/userinfo
        login: https://accounts.google.com/o/oauth2/v2/auth

  flyway:
    enabled: false
  redis:
    host: 127.0.0.1
    port: 6379
jwt:
  secret: my-best-recipe-12312312312312-2312312313
  access-token-expiry: 1296000000
  refresh-token-expiry: 2592000000
  access-token-header: Authorization
  refresh-token-header: Refresh-Token
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
swagger:
  url: http://localhost:8080
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: ${jpa.ddl_auto}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
  flyway:
    enabled: true
    baseline-on-migrate: true
  redis:
    host: ${redis.host}
    port: ${redis.port}
server:
  port: ${spring.server.port}
jwt:
  secret: ${jwt.secret}
  access-token-expiry: ${jwt.access.expire}
  refresh-token-expiry: ${jwt.refresh.expire}
  access-token-header: Authorization
  refresh-token-header: Refresh-Token
swagger:
  url: http://localhost:8080
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: ${jpa.ddl_auto}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
  flyway:
    enabled: true
    baseline-on-migrate: true
  redis:
    host: ${redis.host}
    port: ${redis.port}
server:
  port: ${spring.server.port}
cloud:
  aws:
    stack:
      auto: false
jwt:
  secret: ${jwt.secret}
  access-token-expiry: ${jwt.access.expire}
  refresh-token-expiry: ${jwt.refresh.expire}
  access-token-header: Authorization
  refresh-token-header: Refresh-Token
swagger:
  url: http://localhost:8080